### ISSUE TITLE
Instantiation Error caused by Logger

### ISSUE THREAD

**Issue by faizshukri** [azakordonets/fabricator#21]
After include this package ( `"com.github.azakordonets" % "fabricator_2.11" % "2.1.3"` ), this issue happened (without actually use it yet).

```
Uncaught exception when running package.TestBasic: java.lang.InstantiationError: com.typesafe.scalalogging.Logger
sbt.ForkMain$ForkError: java.lang.InstantiationError: com.typesafe.scalalogging.Logger
        at com.typesafe.scalalogging.Logger$.apply(Logger.scala:32)
        at com.typesafe.scalalogging.StrictLogging$class.$init$(Logging.scala:38)
        at io.gatling.app.Gatling$.<init>(Gatling.scala:30)
        at io.gatling.app.Gatling$.<clinit>(Gatling.scala)
        at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:51)
        at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:50)
        at sbt.ForkMain$Run$2.call(ForkMain.java:296)
        at sbt.ForkMain$Run$2.call(ForkMain.java:286)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Below is my sbt file

```
import io.gatling.sbt.GatlingPlugin

lazy val root = (project in file("."))
  .enablePlugins(GatlingPlugin)
  .settings(
    name := "some stress test",
    scalaVersion := "2.11.8",
    version := "0.1.0",
    libraryDependencies ++= Seq(
      "io.gatling.highcharts"      % "gatling-charts-highcharts" % "2.2.3" % "test",
      "io.gatling"                 % "gatling-test-framework"    % "2.2.3" % "test",
      "org.apache.commons"         % "commons-lang3"             % "3.5",
      "com.github.azakordonets"    % "fabricator_2.11"           % "2.1.3"
    )
  )
```

Is there anything that I'm missing?

**Comment by azakordonets** [comment]
I know that there's a problem with using this library in the multithreaded environment. I'm working on a fix right now, but from logs you're showing i don't see any error pointing to the fabricator library . I see some error in scala logger

**Comment by Arnold1** [comment]
hi, i see a similar issue but dont use your lib. see: 
```java.lang.InstantiationError: com.typesafe.scalalogging.Logger```
any idea what is the problem and how to fix it?

**Comment by azakordonets** [comment]
@Arnold1 could be dependency issue or could be some compatibility issue between your scala version and some lib that you use. Hard to say

**Comment by Arnold1** [comment]
how to figure it out? i run it on databricks and use gradle to build the jar file....

**Comment by azakordonets** [comment]
@Arnold1 sorry, but it's hard for me to suggest anything remotely. You need to look more into stacktrace and google the error
