### ISSUE TITLE
 gatling-highcharts publish error

### ISSUE THREAD

**Issue by didahy** [azakordonets/fabricator#22]
I have executed  compiling gatling and gatling-highcharts,and  publishlocal gatling. But there is an error when i publish   gatling-highcharts:
sbt publishLocal publishM2

error] (gatling-charts-highcharts-bundle/universal:packageBin) java.io.IOExcept
ion: Cannot run program "zip" (in directory "C:\Users\xxxxx\AppData\Local\Tem
p\sbt_ef52f7e2\gatling-charts-highcharts-bundle-3.0.0-SNAPSHOT"): CreateProcess
error=2, system can't find path。

The path "C:\Users\xxxxx\AppData\Local\Tem
p\sbt_ef52f7e2\gatling-charts-highcharts-bundle-3.0.0-SNAPSHOT" doesn't exist._

detail log as follows:
[info]  delivering ivy file to E:\git\gatling-highcha
rts\gatling-charts-highcharts-bundle\target\ivy-3.0.0-SNAPSHOT.xml
[info] Main Scala API documentation toE:\git\gatling
-highcharts\gatling-charts-highcharts\target\api...
[info] Reformatted 29 Scala sources {file:/E:/git/gatling-highcharts/}gatling-charts
-highcharts(compile).
model contains 41 documentable templates
[info] Main Scala API documentation successful.
[info] PackagingE:\git\gatling-highcharts\gatling-ch
arts-highcharts\target\gatling-charts-highcharts-3.0.0-SNAPSHOT-javadoc.jar ...
[info] Done packaging.
[info]  published gatling-charts-highcharts to f:\sbt\local\io.gatling.highchart
s\gatling-charts-highcharts\3.0.0-SNAPSHOT\poms\gatling-charts-highcharts.pom
[info]  published gatling-charts-highcharts to f:\sbt\local\io.gatling.highchart
s\gatling-charts-highcharts\3.0.0-SNAPSHOT\jars\gatling-charts-highcharts.jar
[info]  published gatling-charts-highcharts to f:\sbt\local\io.gatling.highchart
s\gatling-charts-highcharts\3.0.0-SNAPSHOT\srcs\gatling-charts-highcharts-source
s.jar
[info]  published gatling-charts-highcharts to f:\sbt\local\io.gatling.highchart
s\gatling-charts-highcharts\3.0.0-SNAPSHOT\docs\gatling-charts-highcharts-javado
c.jar
[info]  published ivy to f:\sbt\local\io.gatling.highcharts\gatling-charts-highc
harts\3.0.0-SNAPSHOT\ivys\ivy.xml
java.io.IOException: Cannot run program "zip" (in directory "C:\Users\xxxxxx\A
ppData\Local\Temp\sbt_ef52f7e2\gatling-charts-highcharts-bundle-3.0.0-SNAPSHOT")
: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(Unknown Source)
        at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
        at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:126)
        at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:154)
        at com.typesafe.sbt.packager.universal.ZipHelper$$anonfun$zipNative$1.ap
ply(ZipHelper.scala:35)
        at com.typesafe.sbt.packager.universal.ZipHelper$$anonfun$zipNative$1.ap
ply(ZipHelper.scala:23)
        at sbt.IO$.withTemporaryDirectory(IO.scala:344)
        at com.typesafe.sbt.packager.universal.ZipHelper$.zipNative(ZipHelper.sc
ala:23)
        at com.typesafe.sbt.packager.universal.Archives$.makeNativeZip(Archives.
scala:24)
        at com.typesafe.sbt.packager.universal.UniversalPlugin$$anonfun$useNativ
eZip$1.apply(UniversalPlugin.scala:53)
        at com.typesafe.sbt.packager.universal.UniversalPlugin$$anonfun$useNativ
eZip$1.apply(UniversalPlugin.scala:53)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
8)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
8)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestric
tions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        at java.lang.ProcessBuilder.start(Unknown Source)
        at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
        at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:126)
        at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:154)
        at com.typesafe.sbt.packager.universal.ZipHelper$$anonfun$zipNative$1.ap
ply(ZipHelper.scala:35)
        at com.typesafe.sbt.packager.universal.ZipHelper$$anonfun$zipNative$1.ap
ply(ZipHelper.scala:23)
        at sbt.IO$.withTemporaryDirectory(IO.scala:344)
        at com.typesafe.sbt.packager.universal.ZipHelper$.zipNative(ZipHelper.sc
ala:23)
        at com.typesafe.sbt.packager.universal.Archives$.makeNativeZip(Archives.
scala:24)
        at com.typesafe.sbt.packager.universal.UniversalPlugin$$anonfun$useNativ
eZip$1.apply(UniversalPlugin.scala:53)
        at com.typesafe.sbt.packager.universal.UniversalPlugin$$anonfun$useNativ
eZip$1.apply(UniversalPlugin.scala:53)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
8)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
8)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestric
tions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] (gatling-charts-highcharts-bundle/universal:packageBin) java.io.IOExcept
ion: Cannot run program "zip" (in directory "C:\Users\xxxxxx\AppData\Local\Tem
p\sbt_ef52f7e2\gatling-charts-highcharts-bundle-3.0.0-SNAPSHOT"): CreateProcess
error=2, 系统找不到指定的文件。

**Comment by azakordonets** [comment]
There's a problem with using this problem in multithreaded environment. I'm working on fixing that . Sorry about that
